[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "indoor_sun"
version = "0.1.0"
dependencies = ["pillow>=10.3.0"]
authors = [
    { name="lnxd" }
]

[tool.setuptools]
packages = ["custom_components.indoor_sun"] 